export { api, apiRequest, ApiError, setAuthToken, getAuthToken, setAdminAuthToken, getAdminAuthToken, clearAuthSession, AUTH_UNAUTHORIZED_EVENT } from './api-client';
export type {
  User,
  AdminUser,
  Application,
  ApplicantType,
  ApplicationStatus,
  CreateApplicationDto,
  Loan,
  LoanStatus,
  PaymentScheduleItem,
  ScheduleItemStatus,
  PaymentRequest,
  PaymentRequestStatus,
  CreatePaymentRequestDto,
  Payment,
  Notification,
  FileAttachment,
  OwnerType,
  ContactMessage,
  CreateContactMessageDto,
  CalculatorEstimate,
  CalculatorEstimateDto,
  ClientSummary,
  ClientDetail,
  ApplicationsQuery,
  PaymentRequestsQuery,
  ClientsQuery,
  RequestOtpResponse,
  VerifyOtpResponse,
  AdminLoginResponse,
} from './types';
